import { describe, it, expect } from "vitest";
import { execSync } from "child_process";
import { resolve } from "path";

const CLI_PATH = resolve(__dirname, "../dist/cli.js");

function run(args: string): string {
  return execSync(`node ${CLI_PATH} ${args}`, { encoding: "utf-8" }).trim();
}

describe("lytos CLI", () => {
  it("shows help", () => {
    const output = run("--help");
    expect(output).toContain("Lytos");
    expect(output).toContain("Options:");
  });

  it("shows version", () => {
    const output = run("--version");
    expect(output).toMatch(/^\d+\.\d+\.\d+$/);
  });

  /**
   * ISS-0113 left a field note: "re-sync the help every time a command ships".
   * A note is not a gate — this is. The Commands block is generated by
   * commander and cannot drift; the hand-written Examples block can, and a
   * command with no example is a command nobody discovers.
   */
  it("gives every registered command an example", () => {
    const output = run("--help");
    const commandsBlock = output.slice(output.indexOf("Commands:"), output.indexOf("Examples:"));
    const examplesBlock = output.slice(output.indexOf("Examples:"));

    const verbs = commandsBlock
      .split("\n")
      .map((line) => line.match(/^\s{2}([a-z][a-z-]*)\s/))
      .filter((m): m is RegExpMatchArray => m !== null)
      .map((m) => m[1])
      .filter((verb) => verb !== "help"); // commander builtin, not a Lytos verb

    expect(verbs.length).toBeGreaterThan(20); // guard against a parse that silently matches nothing
    const undocumented = verbs.filter((verb) => !examplesBlock.includes(`lyt ${verb}`));
    expect(undocumented).toEqual([]);
  });
});
